# Use a stable Debian release
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV OMP_NUM_THREADS=1 \
    OPENBLAS_NUM_THREADS=1 \
    MKL_NUM_THREADS=1 \
    NUMEXPR_NUM_THREADS=1

ARG TORCH_BASE="--index-url https://download.pytorch.org/whl/cpu"
# Install system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    net-tools \
    iputils-ping \
    iproute2 \
    nano \
    curl \
    ethtool \
    sed \
    iperf3 \
    tcpdump \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Create virtual environment and install Python packages
RUN python3 -m venv venv \
 && ./venv/bin/pip install --upgrade pip setuptools wheel \
 && ./venv/bin/pip install \
    flwr==1.20.0 \
    psutil==7.0.0 \
    APScheduler==3.11.0 \
    hydra-core==1.3.2 \
    pyzmq==27.1.0 \
    flwr-datasets==0.5.0 \
    transformers==4.56.1 \
 && ./venv/bin/pip install \
    torch==2.7.0 \
    torchvision==0.22.0 \
    torchaudio==2.7.0 \
    $TORCH_BASE
## Copy application files
#COPY network_stats.sh .
#COPY traffic_monitor.py .
#
## Ensure script executability
#RUN chmod +x network_stats.sh

# Default to an interactive shell
CMD ["/bin/bash"]
